version: "3"
services:
  snipeit:
    image: linuxserver/snipe-it:version-v5.0.12
    container_name: snipe
    restart: always
    volumes:
      - /home/ubuntu/snipe/config:/config
    environment:
      - APP_URL="http://bastionlb.bimtwin.ml"
      - APP_DEBUG=false
      - MYSQL_PORT_3306_TCP_ADDR=<address-from-terraform-output>
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=<username-from-terraform-output>
      - MYSQL_PASSWORD=<password-from-terraform-output>
      - MAIL_ENV_FROM_ADDR=
      - MAIL_ENV_FROM_NAME=BIM Twin
      - MAIL_ENV_ENCRYPTION=tls
      - MAIL_PORT_587_TCP_ADDR=
      - MAIL_PORT_587_TCP_PORT=587
      - MAIL_ENV_USERNAME=
      - MAIL_ENV_PASSWORD=
      - PGID=1000
      - PUID=1000
    ports:
      - "80:80"